image: node:10.15.3

pipelines:

  branches:
    '{master,release,develop}':
      - step:
          caches:
          - node
          script:
          - ./test.sh
          - pipe: atlassian/aws-s3-deploy:0.3.8
            variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'us-east-2'
                S3_BUCKET: 'bodhala-ui/$BITBUCKET_BRANCH'
                LOCAL_PATH: '$(pwd)'
                ACL: 'public-read'          
          
  pull-requests:
    '**':
      - step:
          caches:
          - node
          script:
          - ./test.sh

definitions:
  caches:
    chrome: /usr/bin/xvfb-chrome

