image: node:10.15.3

pipelines:

  branches:
    '{master,release}':
      - step:
          caches:
          - node
          script:
          - ./test.sh
  pull-requests:
    '**':
      - step:
          caches:
          - node
          script:
          - ./test.sh

definitions:
  caches:
    chrome: /usr/bin/xvfb-chrome

