export const MOCK_CLIENT_CONFIGS = {
  "result": [{
    "id": 10172,
    "org_id": null,
    "client_id": 190,
    "user_id": null,
    "description": "Past Savings",
    "name": "analytics.pastsavings",
    "value": null,
    "json_config": {
      "bb_start_date": "2019-04-01",
      "meetings_start_date": "2018-06-26",
      "overstaffing_number": 3,
      "overstaffing_percent": 0.2,
      "rate_increase_percent": 0.01,
      "percent_annual_increase": 0.03
    },
    "created_by": 13,
    "created_on": "2021-02-26T17:14:25.778338",
    "deleted_by": null,
    "deleted_on": null,
    "modified_by": null,
    "modified_on": "2021-03-03T20:01:00.048294"
  }, {
    "id": 9925,
    "org_id": null,
    "client_id": 190,
    "user_id": null,
    "description": "Generic Filter 1 Display Name",
    "name": "analytics.genericFilter1.name",
    "value": "Handling Office DS",
    "json_config": {
      "id": 4,
      "name": "Practice Areas"
    },
    "created_by": 13,
    "created_on": "2018-07-23T15:14:41.182000",
    "deleted_by": null,
    "deleted_on": null,
    "modified_by": 13,
    "modified_on": "2020-03-26T12:53:27.205593"
  }, {
    "id": 10158,
    "org_id": null,
    "client_id": 190,
    "user_id": null,
    "description": "remove firmSize",
    "name": "analytics.exclude.filter",
    "value": "firmSize",
    "json_config": null,
    "created_by": 13,
    "created_on": "2020-03-25T18:41:22.331245",
    "deleted_by": null,
    "deleted_on": null,
    "modified_by": null,
    "modified_on": "2020-03-25T18:41:22.331245"
  }, {
    "id": 10156,
    "org_id": null,
    "client_id": 190,
    "user_id": null,
    "description": "remove genericFilter2",
    "name": "analytics.exclude.filter",
    "value": "genericFilter2",
    "json_config": null,
    "created_by": 13,
    "created_on": "2020-03-25T18:38:15.633980",
    "deleted_by": null,
    "deleted_on": null,
    "modified_by": null,
    "modified_on": "2020-03-25T18:38:15.633980"
  }, {
    "id": 10155,
    "org_id": null,
    "client_id": 190,
    "user_id": null,
    "description": "genericFilter12 Display Name",
    "name": "analytics.genericFilter12.name",
    "value": "PA for AIG",
    "json_config": {
      "id": 4,
      "name": "Practice Areas"
    },
    "created_by": 13,
    "created_on": "2020-03-25T18:34:43.096177",
    "deleted_by": null,
    "deleted_on": null,
    "modified_by": null,
    "modified_on": "2020-03-25T18:34:43.096177"
  }, {
    "id": 10149,
    "org_id": null,
    "client_id": 190,
    "user_id": null,
    "description": "genericFilter11 Display Name",
    "name": "analytics.genericFilter11.name",
    "value": "Gen Filter 11",
    "json_config": {
      "id": 2,
      "name": "Internal"
    },
    "created_by": 13,
    "created_on": "2020-03-25T16:42:28.097584",
    "deleted_by": null,
    "deleted_on": null,
    "modified_by": null,
    "modified_on": "2020-03-25T16:42:28.097584"
  }, {
    "id": 10144,
    "org_id": null,
    "client_id": 190,
    "user_id": null,
    "description": "genericFilter9 Display Name",
    "name": "analytics.genericFilter9.name",
    "value": "Generic Filter 9 NEW",
    "json_config": {
      "id": 3,
      "name": "Matters"
    },
    "created_by": 13,
    "created_on": "2020-03-24T13:10:54.988957",
    "deleted_by": null,
    "deleted_on": null,
    "modified_by": 13,
    "modified_on": "2020-03-25T18:47:19.588975"
  }, {
    "id": 9988,
    "org_id": null,
    "client_id": 190,
    "user_id": null,
    "description": "Timekeeper Grade filter for AIG",
    "name": "analytics.genericFilter7.name",
    "value": "Timekeeper Grade",
    "json_config": null,
    "created_by": 13,
    "created_on": "2019-08-08T21:39:48.631606",
    "deleted_by": null,
    "deleted_on": null,
    "modified_by": 13,
    "modified_on": "2020-03-24T13:37:51.200304"
  }, {
    "id": 9990,
    "org_id": null,
    "client_id": 190,
    "user_id": null,
    "description": "Handling Office # filter for AIG",
    "name": "analytics.genericFilter10.name",
    "value": "Handling Office #",
    "json_config": null,
    "created_by": 13,
    "created_on": "2019-08-08T21:47:00.716758",
    "deleted_by": null,
    "deleted_on": null,
    "modified_by": null,
    "modified_on": "2020-03-23T15:28:49.675419"
  }, {
    "id": 9989,
    "org_id": null,
    "client_id": 190,
    "user_id": null,
    "description": "Timekeeper Grade filter for AIG",
    "name": "analytics.genericFilter8.name",
    "value": "Matter Status",
    "json_config": null,
    "created_by": 13,
    "created_on": "2019-08-08T21:44:16.661095",
    "deleted_by": null,
    "deleted_on": null,
    "modified_by": null,
    "modified_on": "2020-03-23T15:28:49.675419"
  }, {
    "id": 9930,
    "org_id": null,
    "client_id": 190,
    "user_id": null,
    "description": "Generic Filter 6 Display Name",
    "name": "analytics.genericFilter6.name",
    "value": "Firm Type DS",
    "json_config": null,
    "created_by": 13,
    "created_on": "2018-07-23T15:14:41.542368",
    "deleted_by": null,
    "deleted_on": null,
    "modified_by": null,
    "modified_on": "2020-03-23T15:28:49.675419"
  }, {
    "id": 9929,
    "org_id": null,
    "client_id": 190,
    "user_id": null,
    "description": "Generic Filter 5 Display Name",
    "name": "analytics.genericFilter5.name",
    "value": "Matter Speciality CD",
    "json_config": null,
    "created_by": 13,
    "created_on": "2018-07-23T15:14:41.475277",
    "deleted_by": null,
    "deleted_on": null,
    "modified_by": null,
    "modified_on": "2020-03-23T15:28:49.675419"
  }, {
    "id": 9927,
    "org_id": null,
    "client_id": 190,
    "user_id": null,
    "description": "Generic Filter 3 Display Name",
    "name": "analytics.genericFilter3.name",
    "value": "Major Sub LOB",
    "json_config": null,
    "created_by": 13,
    "created_on": "2018-07-23T15:14:41.342650",
    "deleted_by": null,
    "deleted_on": null,
    "modified_by": null,
    "modified_on": "2020-03-23T15:28:49.675419"
  }, {
    "id": 9926,
    "org_id": null,
    "client_id": 190,
    "user_id": null,
    "description": "Generic Filter 2 Display Name",
    "name": "analytics.genericFilter2.name",
    "value": "Major LOB",
    "json_config": null,
    "created_by": 13,
    "created_on": "2018-07-23T15:14:41.256808",
    "deleted_by": null,
    "deleted_on": null,
    "modified_by": null,
    "modified_on": "2020-03-23T15:28:49.675419"
  }, {
    "id": 9928,
    "org_id": null,
    "client_id": 190,
    "user_id": null,
    "description": "Generic Filter 4 Display Name",
    "name": "analytics.genericFilter4.name",
    "value": "Sub LOB Name",
    "json_config": null,
    "created_by": 13,
    "created_on": "2018-07-23T15:14:41.410152",
    "deleted_by": null,
    "deleted_on": null,
    "modified_by": null,
    "modified_on": "2020-03-23T15:28:49.675419"
  }, {
    "id": 9986,
    "org_id": null,
    "client_id": 190,
    "user_id": null,
    "description": "Remove Reporting Office filter for AIG",
    "name": "analytics.exclude.filter",
    "value": "offices",
    "json_config": null,
    "created_by": 13,
    "created_on": "2019-08-08T21:20:53.260540",
    "deleted_by": null,
    "deleted_on": null,
    "modified_by": null,
    "modified_on": "2019-08-08T21:20:53.260540"
  }, {
    "id": 9987,
    "org_id": null,
    "client_id": 190,
    "user_id": null,
    "description": "Remove Firm Type filter for AIG",
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "json_config": null,
    "created_by": 13,
    "created_on": "2019-08-08T21:23:16.446999",
    "deleted_by": null,
    "deleted_on": null,
    "modified_by": null,
    "modified_on": "2020-03-23T15:28:49.675419"
  }, {
    "id": 9983,
    "org_id": null,
    "client_id": 190,
    "user_id": null,
    "description": "AIG default lawfirm discount (Expressed as a percent between 0.00 and 1.00",
    "name": "analytics.lawfirm.discount.default",
    "value": "0.03",
    "json_config": null,
    "created_by": null,
    "created_on": "2019-04-24T02:56:49.969783",
    "deleted_by": null,
    "deleted_on": null,
    "modified_by": null,
    "modified_on": "2019-04-24T02:56:49.969783"
  }],
  "error": null
}

export const MOCK_DISTINCT_NAMES = {
  "result": ["analytics.exclude.filter", "analytics.genericFilter1.name", "analytics.genericFilter10.name", "analytics.genericFilter11.name", "analytics.genericFilter12.name", "analytics.genericFilter2.name", "analytics.genericFilter3.name", "analytics.genericFilter4.name", "analytics.genericFilter5.name", "analytics.genericFilter6.name", "analytics.genericFilter7.name", "analytics.genericFilter8.name", "analytics.genericFilter9.name", "analytics.lawfirm.discount.default", "analytics.pastsavings", "analytics.reportcard.config", "analytics.summary.advanced", "analytics.summary.splitassistants", "analytics.tkclass.source", "saml", "sso_only"],
  "error": null
}
export const MOCK_SAMPLE_CONFIGS = {
  "result": [{
    "name": "analytics.exclude.filter",
    "value": "firmSize",
    "json_config": null
  }, {
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "json_config": null
  }, {
    "name": "analytics.exclude.filter",
    "value": "genericFilter2",
    "json_config": null
  }, {
    "name": "analytics.exclude.filter",
    "value": "offices",
    "json_config": null
  }],
  "error": null
}
export const MOCK_CLIENTS_CONFIGS_EXTENDED = {
  "result": [{
    "id": 1,
    "client_id": 47,
    "client_name": "Ventas",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.tkclass.source",
    "value": "import",
    "description": null,
    "json_config": null
  }, {
    "id": 26,
    "client_id": 87,
    "client_name": "Stryker",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter2.name",
    "value": "Substantive Law Tier 1",
    "description": "Generic Filter 2 Display Name Config",
    "json_config": null
  }, {
    "id": 27,
    "client_id": 87,
    "client_name": "Stryker",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter3.name",
    "value": "Substantive Law Tier 2",
    "description": "Generic Filter 3 Display Name Config",
    "json_config": null
  }, {
    "id": 28,
    "client_id": 87,
    "client_name": "Stryker",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter4.name",
    "value": "Business Unit Tier 1",
    "description": "Generic Filter 4 Display Name Config",
    "json_config": null
  }, {
    "id": 29,
    "client_id": 87,
    "client_name": "Stryker",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter5.name",
    "value": "Business Unit Tier 2",
    "description": "Generic Filter 5 Display Name Config",
    "json_config": null
  }, {
    "id": 30,
    "client_id": 89,
    "client_name": "State Farm",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter1.name",
    "value": "Matter Sub-Type",
    "description": "Generic Filter 1 Display Name",
    "json_config": null
  }, {
    "id": 31,
    "client_id": 89,
    "client_name": "State Farm",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter2.name",
    "value": "Counsel Big",
    "description": "Generic Filter 2 Display Name",
    "json_config": null
  }, {
    "id": 32,
    "client_id": 89,
    "client_name": "State Farm",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter3.name",
    "value": "Company Type",
    "description": "Generic Filter 3 Display Name",
    "json_config": null
  }, {
    "id": 33,
    "client_id": 89,
    "client_name": "State Farm",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter4.name",
    "value": "Team Lead",
    "description": "Generic Filter 4 Display Name",
    "json_config": null
  }, {
    "id": 34,
    "client_id": 89,
    "client_name": "State Farm",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter5.name",
    "value": "CAUSE OF LOSS",
    "description": "Generic Filter 5 Display Name",
    "json_config": null
  }, {
    "id": 8626,
    "client_id": 103,
    "client_name": "Astellas",
    "org_id": 155,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter1.name",
    "value": "Matter Sub-type",
    "description": "Generic Filter 1 Display Name",
    "json_config": null
  }, {
    "id": 8636,
    "client_id": 103,
    "client_name": "Astellas",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.summary.advanced",
    "value": "false",
    "description": null,
    "json_config": null
  }, {
    "id": 8637,
    "client_id": 89,
    "client_name": "State Farm",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.summary.splitassistants",
    "value": "true",
    "description": null,
    "json_config": null
  }, {
    "id": 9435,
    "client_id": 89,
    "client_name": "State Farm",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter6.name",
    "value": "Cat Codes",
    "description": "Generic Filter 6 Display Name",
    "json_config": null
  }, {
    "id": 9436,
    "client_id": 113,
    "client_name": "Bloomberg",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter1.name",
    "value": "Matter Practice Group",
    "description": "Generic Filter 1 Display Name Config",
    "json_config": null
  }, {
    "id": 9437,
    "client_id": 113,
    "client_name": "Bloomberg",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter10.name",
    "value": "Matter Status",
    "description": "Generic Filter 10 Display Name Config",
    "json_config": null
  }, {
    "id": 9438,
    "client_id": 113,
    "client_name": "Bloomberg",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter2.name",
    "value": "Matter Classification",
    "description": "Generic Filter 2 Display Name Config",
    "json_config": null
  }, {
    "id": 9439,
    "client_id": 113,
    "client_name": "Bloomberg",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter3.name",
    "value": "Bloomberg Company",
    "description": "Generic Filter 3 Display Name Config",
    "json_config": null
  }, {
    "id": 9440,
    "client_id": 113,
    "client_name": "Bloomberg",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter4.name",
    "value": "Matter Region",
    "description": "Generic Filter 4 Display Name Config",
    "json_config": null
  }, {
    "id": 9441,
    "client_id": 110,
    "client_name": "Blackrock",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.summary.advanced",
    "value": "true",
    "description": null,
    "json_config": null
  }, {
    "id": 9442,
    "client_id": 110,
    "client_name": "Blackrock",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter1.name",
    "value": "Matter ID",
    "description": "Generic Filter 1 Display Name Config",
    "json_config": null
  }, {
    "id": 9443,
    "client_id": 110,
    "client_name": "Blackrock",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter4.name",
    "value": "Adj Rule Description",
    "description": "Generic Filter 4 Display Name Config",
    "json_config": null
  }, {
    "id": 9444,
    "client_id": 110,
    "client_name": "Blackrock",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter2.name",
    "value": "Charge Type",
    "description": "Generic Filter 2 Display Name Config",
    "json_config": null
  }, {
    "id": 9445,
    "client_id": 110,
    "client_name": "Blackrock",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter3.name",
    "value": "Charge Code Type",
    "description": "Generic Filter 3 Display Name Config",
    "json_config": null
  }, {
    "id": 9446,
    "client_id": 89,
    "client_name": "State Farm",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter7.name",
    "value": "Matter Number",
    "description": "Generic Filter 7 Name",
    "json_config": null
  }, {
    "id": 9839,
    "client_id": 120,
    "client_name": "Bridgewater",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter1.name",
    "value": "Matter Type",
    "description": "Generic Filter 1 Display Name",
    "json_config": null
  }, {
    "id": 9840,
    "client_id": 120,
    "client_name": "Bridgewater",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter2.name",
    "value": "Org Unit",
    "description": "Generic Filter 2 Display Name",
    "json_config": null
  }, {
    "id": 9846,
    "client_id": null,
    "client_name": null,
    "org_id": null,
    "user_id": 436,
    "user_name": "Eric Laffey",
    "email": "eric.laffey.bqje@statefarm.com",
    "name": "analytics.access.control",
    "value": null,
    "description": "sf FL and CO",
    "json_config": {
      "field": "offices",
      "value": ["CO", "FL"]
    }
  }, {
    "id": 9858,
    "client_id": null,
    "client_name": "Acme Corp",
    "org_id": 63,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.reportcard.config",
    "value": null,
    "description": "Analytics Report Card Config",
    "json_config": {
      "leverage_weight": 0.25,
      "partner_rate_weight": 2.5,
      "block_billing_weight": 2.5,
      "associate_rate_weight": 0.75,
      "nonlawyer_rate_weight": 0.25,
      "avg_matter_cost_weight": 1,
      "hourly_leverage_weight": 0.75
    }
  }, {
    "id": 9859,
    "client_id": null,
    "client_name": "Bloomberg",
    "org_id": 161,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.reportcard.config",
    "value": null,
    "description": "Analytics Report Card Config",
    "json_config": {
      "leverage_weight": 1,
      "partner_rate_weight": 2.5,
      "block_billing_weight": 2.5,
      "associate_rate_weight": 1,
      "nonlawyer_rate_weight": 2,
      "avg_matter_cost_weight": 1,
      "hourly_leverage_weight": 1
    }
  }, {
    "id": 9893,
    "client_id": 89,
    "client_name": "State Farm",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter8.name",
    "value": "Type of Counsel",
    "description": "Generic Filter 8 Display Name",
    "json_config": null
  }, {
    "id": 9925,
    "client_id": 190,
    "client_name": "AIG Test",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter1.name",
    "value": "Handling Office DS",
    "description": "Generic Filter 1 Display Name",
    "json_config": null
  }, {
    "id": 9926,
    "client_id": 190,
    "client_name": "AIG Test",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter2.name",
    "value": "Major LOB",
    "description": "Generic Filter 2 Display Name",
    "json_config": null
  }, {
    "id": 9927,
    "client_id": 190,
    "client_name": "AIG Test",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter3.name",
    "value": "Major Sub LOB",
    "description": "Generic Filter 3 Display Name",
    "json_config": null
  }, {
    "id": 9928,
    "client_id": 190,
    "client_name": "AIG Test",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter4.name",
    "value": "Sub LOB Name",
    "description": "Generic Filter 4 Display Name",
    "json_config": null
  }, {
    "id": 9929,
    "client_id": 190,
    "client_name": "AIG Test",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter5.name",
    "value": "Matter Speciality CD",
    "description": "Generic Filter 5 Display Name",
    "json_config": null
  }, {
    "id": 9930,
    "client_id": 190,
    "client_name": "AIG Test",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter6.name",
    "value": "Firm Type DS",
    "description": "Generic Filter 6 Display Name",
    "json_config": null
  }, {
    "id": 9958,
    "client_id": null,
    "client_name": "Bloomberg",
    "org_id": 161,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "sso_only",
    "value": "True",
    "description": "Everyone use SAML",
    "json_config": null
  }, {
    "id": 9959,
    "client_id": null,
    "client_name": "Bloomberg",
    "org_id": 161,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "saml",
    "value": "{\n    \"idp_entity_id\" : \"https://app.onelogin.com/saml/metadata/00a9478f-ea3c-48b3-95f7-eda0a5d6ddba\",\n    \"security\" : {\n        \"authnRequestsSigned\": true\n    }\n}",
    "description": "Saml Settings",
    "json_config": null
  }, {
    "id": 9960,
    "client_id": null,
    "client_name": "State Farm",
    "org_id": 154,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "saml",
    "value": "{\n    \"idp_entity_id\" : \"sf-bodhala-idp-int\",\n    \"security\" : {\n        \"nameIdEncrypted\": false,\n        \"authnRequestsSigned\": false,\n        \"logoutRequestSigned\": true,\n        \"logoutResponseSigned\": true,\n        \"signMetadata\": true,\n        \"wantMessagesSigned\": false,\n        \"wantAssertionsSigned\": true,\n        \"wantNameId\" : true,\n        \"wantNameIdEncrypted\": false,\n        \"wantAssertionsEncrypted\": false\n    }\n}",
    "description": "Saml Settings",
    "json_config": null
  }, {
    "id": 9963,
    "client_id": null,
    "client_name": "Bridgewater",
    "org_id": 162,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "saml",
    "value": "{\n    \"idp_entity_id\" : \"https://app.onelogin.com/saml/metadata/f91358c9-bccd-4ca8-b2ee-a5a8138af11c\",\n    \"security\" : {\n        \"wantMessagesSigned\": true,\n        \"wantAssertionsSigned\": false,\n        \"wantAssertionsEncrypted\": false\n    }\n}",
    "description": "Saml Settings",
    "json_config": null
  }, {
    "id": 9966,
    "client_id": 456,
    "client_name": "AIG Claims",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter1.name",
    "value": "Handling Office Name",
    "description": "Generic Filter 1 Display Name",
    "json_config": null
  }, {
    "id": 9967,
    "client_id": 456,
    "client_name": "AIG Claims",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter2.name",
    "value": "Major LOB",
    "description": "Generic Filter 2 Display Name",
    "json_config": null
  }, {
    "id": 9968,
    "client_id": 456,
    "client_name": "AIG Claims",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter3.name",
    "value": "Major Sub LOB",
    "description": "Generic Filter 3 Display Name",
    "json_config": null
  }, {
    "id": 9969,
    "client_id": 456,
    "client_name": "AIG Claims",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter4.name",
    "value": "Product",
    "description": "Generic Filter 4 Display Name",
    "json_config": null
  }, {
    "id": 9970,
    "client_id": 456,
    "client_name": "AIG Claims",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter5.name",
    "value": "Matter Speciality CD",
    "description": "Generic Filter 5 Display Name",
    "json_config": null
  }, {
    "id": 9971,
    "client_id": 456,
    "client_name": "AIG Claims",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter6.name",
    "value": "Firm Type DS",
    "description": "Generic Filter 6 Display Name",
    "json_config": null
  }, {
    "id": 9972,
    "client_id": 456,
    "client_name": "AIG Claims",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter7.name",
    "value": "Timekeeper Grade",
    "description": "Generic Filter 7 Display Name",
    "json_config": null
  }, {
    "id": 9973,
    "client_id": 456,
    "client_name": "AIG Claims",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter8.name",
    "value": "Matter Status",
    "description": "Generic Filter 8 Display Name",
    "json_config": null
  }, {
    "id": 9974,
    "client_id": 456,
    "client_name": "AIG Claims",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter9.name",
    "value": "Matter Type Code",
    "description": "Generic Filter 9 Display Name",
    "json_config": null
  }, {
    "id": 9975,
    "client_id": 456,
    "client_name": "AIG Claims",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter10.name",
    "value": "Handling Office Code",
    "description": "Generic Filter 10 Display Name",
    "json_config": null
  }, {
    "id": 9979,
    "client_id": null,
    "client_name": "State Farm",
    "org_id": 154,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "sso_only",
    "value": "True",
    "description": "Everyone use SAML",
    "json_config": null
  }, {
    "id": 9982,
    "client_id": null,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.lawfirm.discount.default",
    "value": "0.03",
    "description": "Bodhala default lawfirm discount (Expressed as a percent between 0.00 and 1.00)",
    "json_config": null
  }, {
    "id": 9983,
    "client_id": 190,
    "client_name": "AIG Test",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.lawfirm.discount.default",
    "value": "0.03",
    "description": "AIG default lawfirm discount (Expressed as a percent between 0.00 and 1.00",
    "json_config": null
  }, {
    "id": 9984,
    "client_id": null,
    "client_name": "BNP Paribus",
    "org_id": 400,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "saml",
    "value": "{\n     \"idp_entity_id\" : \"https://idp.staging.echonet/vordel/trust\",\n     \"security\" : {\n         \"nameIdEncrypted\": false,\n         \"authnRequestsSigned\": false,\n         \"logoutRequestSigned\": true,\n         \"logoutResponseSigned\": true,\n         \"signMetadata\": true,\n         \"wantMessagesSigned\": false,\n         \"wantAssertionsSigned\": true,\n         \"wantNameId\" : true,\n         \"wantNameIdEncrypted\": false,\n         \"wantAssertionsEncrypted\": false\n     }\n}",
    "description": "Saml Settings for BNP",
    "json_config": null
  }, {
    "id": 9986,
    "client_id": 190,
    "client_name": "AIG Test",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "offices",
    "description": "Remove Reporting Office filter for AIG",
    "json_config": null
  }, {
    "id": 9988,
    "client_id": 190,
    "client_name": "AIG Test",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter7.name",
    "value": "Timekeeper Grade",
    "description": "Timekeeper Grade filter for AIG",
    "json_config": null
  }, {
    "id": 9989,
    "client_id": 190,
    "client_name": "AIG Test",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter8.name",
    "value": "Matter Status",
    "description": "Timekeeper Grade filter for AIG",
    "json_config": null
  }, {
    "id": 9990,
    "client_id": 190,
    "client_name": "AIG Test",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter10.name",
    "value": "Handling Office #",
    "description": "Handling Office # filter for AIG",
    "json_config": null
  }, {
    "id": 9994,
    "client_id": 89,
    "client_name": "State Farm",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter12.name",
    "value": "THIS IS FILTER TWELVE",
    "description": "genericFilter12 Display Name",
    "json_config": null
  }, {
    "id": 9996,
    "client_id": 41,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 9997,
    "client_id": 43,
    "client_name": "Flatiron Investors/Laurel Touby",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 9998,
    "client_id": 42,
    "client_name": "MWW PR",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 9999,
    "client_id": 44,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10000,
    "client_id": 45,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10001,
    "client_id": 32,
    "client_name": "Novarca North America",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10002,
    "client_id": 27,
    "client_name": "Acme Corp",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10003,
    "client_id": 34,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10004,
    "client_id": 33,
    "client_name": "GoldenTree Asset Management LP",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10005,
    "client_id": 36,
    "client_name": "Self",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10006,
    "client_id": 37,
    "client_name": "Return Path",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10007,
    "client_id": 38,
    "client_name": "Cohlmia LLC",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10008,
    "client_id": 39,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10009,
    "client_id": 35,
    "client_name": "MedGenome",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10010,
    "client_id": 40,
    "client_name": "MWW PR",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10011,
    "client_id": 51,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10012,
    "client_id": 47,
    "client_name": "Ventas",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10013,
    "client_id": 46,
    "client_name": "REIT",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10014,
    "client_id": 48,
    "client_name": "Crest Ultrasonics",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10015,
    "client_id": 49,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10017,
    "client_id": 52,
    "client_name": "United Airlines",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10018,
    "client_id": 53,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10019,
    "client_id": 54,
    "client_name": "United Airlines",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10020,
    "client_id": 55,
    "client_name": "United Airlines",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10021,
    "client_id": 56,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10022,
    "client_id": 57,
    "client_name": "Halcyon LLC",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10023,
    "client_id": 59,
    "client_name": "GoldenTree Asset Management, LP",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10024,
    "client_id": 60,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10025,
    "client_id": 61,
    "client_name": "Bodhala OneLogin Test",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10026,
    "client_id": 62,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10027,
    "client_id": 63,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10028,
    "client_id": 64,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10029,
    "client_id": 65,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10030,
    "client_id": 66,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10031,
    "client_id": 67,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10032,
    "client_id": 68,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10033,
    "client_id": 69,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10034,
    "client_id": 70,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10035,
    "client_id": 71,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10036,
    "client_id": 76,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10037,
    "client_id": 90,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10038,
    "client_id": 79,
    "client_name": "Windows",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10039,
    "client_id": 82,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10040,
    "client_id": 85,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10041,
    "client_id": 89,
    "client_name": "State Farm",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10042,
    "client_id": 88,
    "client_name": "Stryker",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10043,
    "client_id": 93,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10044,
    "client_id": 94,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10045,
    "client_id": 98,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10046,
    "client_id": 101,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10047,
    "client_id": 355,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10048,
    "client_id": 104,
    "client_name": "UnitedLex",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10049,
    "client_id": 124,
    "client_name": "Upload Tests",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10050,
    "client_id": 105,
    "client_name": "AB INBEV",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10051,
    "client_id": 157,
    "client_name": "Blackstone",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10052,
    "client_id": 106,
    "client_name": "Anheuser-Busch LLC",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10053,
    "client_id": 109,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10054,
    "client_id": 190,
    "client_name": "AIG Test",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10055,
    "client_id": 110,
    "client_name": "Blackrock",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10056,
    "client_id": 223,
    "client_name": "Morgan Stanley",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10057,
    "client_id": 111,
    "client_name": "State Farm Wannbe",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10058,
    "client_id": 256,
    "client_name": "Dupe TK Test",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10059,
    "client_id": 113,
    "client_name": "Bloomberg",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10060,
    "client_id": 114,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10061,
    "client_id": 115,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10062,
    "client_id": 116,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10063,
    "client_id": 117,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10064,
    "client_id": 119,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10065,
    "client_id": 388,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10066,
    "client_id": 120,
    "client_name": "Bridgewater",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10067,
    "client_id": 289,
    "client_name": "Expensify",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10068,
    "client_id": 121,
    "client_name": "Tishman Speyer",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10069,
    "client_id": 122,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10070,
    "client_id": 322,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10071,
    "client_id": 123,
    "client_name": "State Farm SSO Test Org",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10072,
    "client_id": 421,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10073,
    "client_id": 72,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10074,
    "client_id": 77,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10075,
    "client_id": 83,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10076,
    "client_id": 91,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10077,
    "client_id": 86,
    "client_name": "Evercore",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10078,
    "client_id": 95,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10079,
    "client_id": 96,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10080,
    "client_id": 97,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10081,
    "client_id": 99,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10082,
    "client_id": 102,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10083,
    "client_id": 107,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10084,
    "client_id": 112,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10085,
    "client_id": 118,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10086,
    "client_id": 80,
    "client_name": "SHAWN'S TEST CLIENT",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10087,
    "client_id": 73,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10088,
    "client_id": 92,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10089,
    "client_id": 74,
    "client_name": "XL Catlin",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10090,
    "client_id": 75,
    "client_name": "Bodhala",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10091,
    "client_id": 78,
    "client_name": "Macquarie",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10092,
    "client_id": 100,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10093,
    "client_id": 81,
    "client_name": "Don't use",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10094,
    "client_id": 84,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10095,
    "client_id": 87,
    "client_name": "Stryker",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10096,
    "client_id": 103,
    "client_name": "Astellas",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10097,
    "client_id": 108,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10098,
    "client_id": 454,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10099,
    "client_id": 457,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10100,
    "client_id": 456,
    "client_name": "AIG Claims",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10101,
    "client_id": 455,
    "client_name": "AIG2",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10102,
    "client_id": 458,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10103,
    "client_id": 459,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10104,
    "client_id": 460,
    "client_name": "3074 Tech",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10105,
    "client_id": 463,
    "client_name": "Tishman Test",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10106,
    "client_id": 461,
    "client_name": "NewClient1",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10107,
    "client_id": 462,
    "client_name": "BNP Paribus",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10108,
    "client_id": 464,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10109,
    "client_id": 465,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10110,
    "client_id": 466,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10111,
    "client_id": 467,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10112,
    "client_id": 468,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10113,
    "client_id": 469,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10114,
    "client_id": 470,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10115,
    "client_id": 471,
    "client_name": "Lockton",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmTypes",
    "description": "Remove firm type filter",
    "json_config": null
  }, {
    "id": 10118,
    "client_id": 121,
    "client_name": "Tishman Speyer",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "courtLocations",
    "description": "remove courtLocations",
    "json_config": null
  }, {
    "id": 10119,
    "client_id": 121,
    "client_name": "Tishman Speyer",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "firmSize",
    "description": "remove firmSize",
    "json_config": null
  }, {
    "id": 10121,
    "client_id": 121,
    "client_name": "Tishman Speyer",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "clientCounsels",
    "description": "remove clientCounsels",
    "json_config": null
  }, {
    "id": 10122,
    "client_id": 121,
    "client_name": "Tishman Speyer",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "linesOfBusiness",
    "description": "remove linesOfBusiness",
    "json_config": null
  }, {
    "id": 10123,
    "client_id": 121,
    "client_name": "Tishman Speyer",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "matters",
    "description": "remove matters",
    "json_config": null
  }, {
    "id": 10127,
    "client_id": 121,
    "client_name": "Tishman Speyer",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "practiceAreas",
    "description": "remove practiceAreas",
    "json_config": null
  }, {
    "id": 10128,
    "client_id": 121,
    "client_name": "Tishman Speyer",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "offices",
    "description": "remove offices",
    "json_config": null
  }, {
    "id": 10129,
    "client_id": 121,
    "client_name": "Tishman Speyer",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "utbmsCodes",
    "description": "remove utbmsCodes",
    "json_config": null
  }, {
    "id": 10130,
    "client_id": 121,
    "client_name": "Tishman Speyer",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "threshold",
    "description": "remove threshold",
    "json_config": null
  }, {
    "id": 10131,
    "client_id": 121,
    "client_name": "Tishman Speyer",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "courtTypes",
    "description": "remove courtTypes",
    "json_config": null
  }, {
    "id": 10132,
    "client_id": null,
    "client_name": "State Farm",
    "org_id": 154,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.taskcost.groupby",
    "value": "firms,matters,practiceAreas,offices,genericFilter1,genericFilter2,genericFilter3,genericFilter4,genericFilter5,genericFilter6,genericFilter7,genericFilter8,courtTypes",
    "description": "config for analytics taskcost",
    "json_config": [{
      "name": "firms",
      "label": "Firms"
    }, {
      "name": "matters",
      "label": "Matters"
    }, {
      "name": "practiceAreas",
      "label": "Practice Areas"
    }, {
      "name": "offices",
      "label": "Offices"
    }, {
      "name": "genericFilter1",
      "label": "Matter Sub-Type"
    }, {
      "name": "genericFilter2",
      "label": "Counsel Big"
    }, {
      "name": "genericFilter3",
      "label": "Company Type"
    }, {
      "name": "genericFilter4",
      "label": "Team Lead"
    }, {
      "name": "genericFilter5",
      "label": "CAUSE OF LOSS"
    }, {
      "name": "genericFilter6",
      "label": "Cat Codes"
    }, {
      "name": "genericFilter7",
      "label": "Matter Number"
    }, {
      "name": "genericFilter8",
      "label": "Type of Counsel"
    }, {
      "name": "courtTypes",
      "label": "Court Types"
    }]
  }, {
    "id": 10136,
    "client_id": null,
    "client_name": "Bodhala OneLogin Test",
    "org_id": 143,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "saml",
    "value": "{\n    \"idp_entity_id\" : \"https://samltest.id/saml/idp\",\n    \"security\" : {\n        \"nameIdEncrypted\": false,\n        \"authnRequestsSigned\": false,\n        \"logoutRequestSigned\": true,\n        \"logoutResponseSigned\": true,\n        \"signMetadata\": true,\n        \"wantMessagesSigned\": false,\n        \"wantAssertionsSigned\": true,\n        \"wantNameId\" : true,\n        \"wantNameIdEncrypted\": false,\n        \"wantAssertionsEncrypted\": false\n    }\n}",
    "description": "Saml Settings for testing (samltest.id)",
    "json_config": null
  }, {
    "id": 10137,
    "client_id": 460,
    "client_name": "3074 Tech",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter1.name",
    "value": "Test",
    "description": "genericFilter1 Display Name",
    "json_config": {
      "id": 1,
      "name": "Firms"
    }
  }, {
    "id": 10138,
    "client_id": null,
    "client_name": "Bloomberg",
    "org_id": 161,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "data.analytics.firm.groupby",
    "value": "unitBilling,rateOfWork",
    "description": "config for analytics firm dashboard",
    "json_config": [{
      "name": "unitBilling",
      "label": "Unit Billing"
    }, {
      "name": "rateOfWork",
      "label": "Rate of Work"
    }]
  }, {
    "id": 10139,
    "client_id": null,
    "client_name": "Astellas",
    "org_id": 155,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "data.analytics.firm.groupby",
    "value": "unitBilling",
    "description": "config for analytics firm dashboard",
    "json_config": [{
      "name": "unitBilling",
      "label": "Unit Billing"
    }]
  }, {
    "id": 10143,
    "client_id": 190,
    "client_name": "AIG Test",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "genericFilter10",
    "description": "remove genericFilter10",
    "json_config": null
  }, {
    "id": 10144,
    "client_id": 27,
    "client_name": "Acme Corp",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter1.name",
    "value": "TEST 1",
    "description": "genericFilter1 Display Name",
    "json_config": {
      "id": 1,
      "name": "Firms"
    }
  }, {
    "id": 10145,
    "client_id": 27,
    "client_name": "Acme Corp",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.genericFilter10.name",
    "value": "TEST 10",
    "description": "genericFilter10 Display Name",
    "json_config": {
      "id": 1,
      "name": "Firms"
    }
  }, {
    "id": 10149,
    "client_id": 27,
    "client_name": "Acme Corp",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "genericFilter1",
    "description": "remove genericFilter1",
    "json_config": null
  }, {
    "id": 10150,
    "client_id": 27,
    "client_name": "Acme Corp",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.exclude.filter",
    "value": "genericFilter10",
    "description": "remove genericFilter10",
    "json_config": null
  }, {
    "id": 10162,
    "client_id": null,
    "client_name": "State Farm",
    "org_id": 154,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.reportcard.config",
    "value": null,
    "description": "Analytics Report Card Config",
    "json_config": {
      "leverage_weight": 0.25,
      "partner_rate_weight": 2.5,
      "block_billing_weight": 2.5,
      "associate_rate_weight": 0.75,
      "nonlawyer_rate_weight": 0.25,
      "avg_matter_cost_weight": 1,
      "hourly_leverage_weight": 0.75
    }
  }, {
    "id": 10163,
    "client_id": null,
    "client_name": "Blackrock",
    "org_id": 159,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.reportcard.config",
    "value": null,
    "description": "Analytics Report Card Config",
    "json_config": {
      "leverage_weight": 0.25,
      "partner_rate_weight": 2.5,
      "block_billing_weight": 2.5,
      "associate_rate_weight": 0.75,
      "nonlawyer_rate_weight": 0.25,
      "avg_matter_cost_weight": 1,
      "hourly_leverage_weight": 0.75
    }
  }, {
    "id": 10173,
    "client_id": 89,
    "client_name": "State Farm",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.afa.rules.disabled",
    "value": "True",
    "description": "Disable Bodhala AFA rules for State Farm",
    "json_config": null
  }, {
    "id": 10175,
    "client_id": 190,
    "client_name": "AIG Test",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.afa.rules.disabled",
    "value": "True",
    "description": "Disable Bodhala AFA rules for AIG",
    "json_config": null
  }, {
    "id": 10176,
    "client_id": null,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.tkmatcher.blacklist",
    "value": null,
    "description": "Default bodhala tk black list",
    "json_config": null
  }, {
    "id": 10182,
    "client_id": null,
    "client_name": null,
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.duplicate.line_item",
    "value": null,
    "description": "Config for duplicate line items",
    "json_config": {
      "excluded_columns": ["id", "raw_id", "created_by", "created_on", "bh_batch_id"],
      "non_updatable_columns": ["id", "raw_id", "created_by", "created_on", "bh_batch_id", "bh_phase", "bh_sub_phase"]
    }
  }, {
    "id": 10183,
    "client_id": 471,
    "client_name": "Lockton",
    "org_id": null,
    "user_id": 865,
    "user_name": "Caroline Herschel",
    "email": "tech+lockton@bodhala.com",
    "name": "matters.table.extracalls",
    "value": null,
    "description": "Custom Column for Generic Filter - Lockton",
    "json_config": [{
      "field": "generic_filter_6",
      "value": "Project Manager"
    }]
  }, {
    "id": 10185,
    "client_id": 190,
    "client_name": "AIG Test",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.afa.rules.debug",
    "value": "true",
    "description": "Enable AFA Plugin debugging",
    "json_config": null
  }, {
    "id": 10186,
    "client_id": 190,
    "client_name": "AIG Test",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.serviceprovider.rules.debug",
    "value": "true",
    "description": "Enable SP Plugin debugging",
    "json_config": null
  }, {
    "id": 10187,
    "client_id": 190,
    "client_name": "AIG Test",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.serviceprovider.rules.disabled",
    "value": "true",
    "description": "Disable the SP Plugin",
    "json_config": null
  }, {
    "id": 10191,
    "client_id": 190,
    "client_name": "AIG Test",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "firms.table.extracalls",
    "value": null,
    "description": "Custom Columns for Generic Filters - AIG, Firms",
    "json_config": [{
      "field": "generic_filter_9",
      "value": "Office"
    }, {
      "field": "generic_filter_6",
      "value": "Defense Type"
    }]
  }, {
    "id": 10194,
    "client_id": null,
    "client_name": "Bloomberg",
    "org_id": 161,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.practice.bodhala.areas",
    "value": "Smart Practice Areas",
    "description": "config for analytics practice areas",
    "json_config": "Smart Practice Areas"
  }, {
    "id": 10195,
    "client_id": null,
    "client_name": "State Farm",
    "org_id": 154,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.practice.bodhala.areas",
    "value": "Smart Practice Areas",
    "description": "config for analytics practice areas",
    "json_config": "Smart Practice Areas"
  }, {
    "id": 10196,
    "client_id": 190,
    "client_name": "AIG Test",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.pastsavings",
    "value": null,
    "description": "Past Savings",
    "json_config": {
      "bb_start_date": "2020-04-01",
      "meetings_start_date": "2019-09-22",
      "overstaffing_number": 3,
      "overstaffing_percent": 0.2,
      "rate_increase_percent": 0.08,
      "percent_annual_increase": 0.03
    }
  }, {
    "id": 10200,
    "client_id": 190,
    "client_name": "AIG Test",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.discounts",
    "value": null,
    "description": "discount_pa_type can have value 'bodhala' or 'client'",
    "json_config": {
      "discount_pa_type": "client",
      "sub_practice_are": "generic_filter_3"
    }
  }, {
    "id": 10201,
    "client_id": null,
    "client_name": "AIG Test",
    "org_id": 232,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.practice.bodhala.areas",
    "value": "Client Practice Areas",
    "description": "config for analytics practice areas",
    "json_config": "Client Practice Areas"
  }, {
    "id": 10202,
    "client_id": 190,
    "client_name": "AIG Test",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "report.card.excludes",
    "value": null,
    "description": "\"TOTAL_SPEND\",\n \"MATTER_COST\",\n \"PARTNER_HOURS\",\n \"ASSOCIATE_HOURS\",\n \"PARALEGAL_HOURS\",\n \"AVG_MATTER_DURATION\",\n \"BLENDED_RATE\",\n \"BODHALA_PRICE_INDEX\",\n \"BLOCK_BILLING\",\n \"PARTNER_RATE\",\n \"ASSOCIATE_RATE\",\n \"PARALEGAL_RATE\"",
    "json_config": ["ASSOCIATE_HOURS"]
  }, {
    "id": 10203,
    "client_id": 105,
    "client_name": "AB INBEV",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "report.card.excludes",
    "value": null,
    "description": "\"TOTAL_SPEND\",\n \"MATTER_COST\",\n \"PARTNER_HOURS\",\n \"ASSOCIATE_HOURS\",\n \"PARALEGAL_HOURS\",\n \"AVG_MATTER_DURATION\",\n \"BLENDED_RATE\",\n \"BODHALA_PRICE_INDEX\",\n \"BLOCK_BILLING\",\n \"PARTNER_RATE\",\n \"ASSOCIATE_RATE\",\n \"PARALEGAL_RATE\"",
    "json_config": ["ASSOCIATE_HOURS"]
  }, {
    "id": 10204,
    "client_id": null,
    "client_name": "AIG Test",
    "org_id": 232,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "analytics.reportcard.config",
    "value": null,
    "description": "Analytics Report Card Config",
    "json_config": {
      "leverage_weight": 0.25,
      "partner_rate_weight": 2.5,
      "block_billing_weight": 2.5,
      "associate_rate_weight": 0.75,
      "nonlawyer_rate_weight": 0.25,
      "avg_matter_cost_weight": 1,
      "hourly_leverage_weight": 0.75
    }
  }, {
    "id": 10205,
    "client_id": 190,
    "client_name": "AIG Test",
    "org_id": null,
    "user_id": null,
    "user_name": " ",
    "email": null,
    "name": "matters.table.extracalls",
    "value": null,
    "description": "Custom Column for Generic Filter - AIG",
    "json_config": [{
      "field": "generic_filter_4",
      "value": "SLT Member"
    }]
  }],
  "error": null
}


