export const FILTERS = {
  "includeExpenses": false,
  "dataFilters": {
    "matters": ["1001", "1002"],
    "practiceAreas": ["EXCESS"],
    "firms": ["AIG", "SF"],
    "threshold": 4,
    "displayThreshold": {
      "thresholdHours": 4,
      "thresholdMins": 0
    },
    "linesOfBusiness": ["CORRUPTION", "LAW"],
    "offices": ["1", "2"],
    "clientCounsels": ["1", "2"],
    "geographies": ['Russia, Moscow', 'USA, NY'],
    "firmSizes": [10, 100],
    "firmTypes": ["1", "2"],
    "cities": ["NY", "BOSTON"],
    "states": ["NY", "BOSTON"],
    "courtLocations": ["1,2", "2,3"],
    "courtTypes": ["1", "2"],
    "utbmsCodes": ["1", "2"],
    "excludeFirms": false,
    "excludeMatters": false,
    "excludePracticeAreas": false,
    "excludeLineOfBusiness": false,
    "excludeOffices": false,
    "excludeClientCounsel": false,
    "excludeGeography": false,
    "excludeFirmType": false,
    "excludeCourtLocations": false,
    "excludeCourtTypes": false,
    "excludeUtbmsCodes": false,
    "excludeOpposingFirms": false,
    "genericFilter1": ["1", "2"],
    "genericFilter2": ["1", "2"],
    "genericFilter3": ["1", "2"],
    "genericFilter4": ["1", "2"],
    "genericFilter5": ["1", "2"],
    "genericFilter6": ["1", "2"],
    "genericFilter7": ["1", "2"],
    "genericFilter8": ["1", "2"],
    "genericFilter9": ["1", "2"],
    "genericFilter10": ["1", "2"],
    "genericFilter11": ["1", "2"],
    "genericFilter12": ["1", "2"],
    "excludeGenericFilter1": false,
    "excludeGenericFilter2": false,
    "excludeGenericFilter3": false,
    "excludeGenericFilter4": false,
    "excludeGenericFilter5": false,
    "excludeGenericFilter6": false,
    "excludeGenericFilter7": false,
    "excludeGenericFilter8": false,
    "excludeGenericFilter9": false,
    "excludeGenericFilter10": false,
    "excludeGenericFilter11": false,
    "excludeGenericFilter12": false,
    "matterOpenDates": {start: '2019-01-01', end: '2019-06-24'},
    "matterCloseDates": {start: '2019-01-01', end: '2019-06-24'},
    "dayOfMatter": {},
    "dayOfMatterRange": "First",
    "opposingFirms": ['1', '2'],
    "firmMatterCounts": [10, 100],
    "rangeTagFilters": {
      k1 : { filteredRange: [1, 2], range: [10, 20], tagtypeid: 100},
    },
    "selectTagFilters": {k2: {value: 1, tagtypeid: 100}},
    "multiSelectTagFilters": {k3: {value: [1,2,3], tagtypeid: 100}},
    "loadedFilters": [],
    "chosenFilters": ["practiceAreas", "firms"],
    "updatedOptions": {},
    "minFirmSize": 10,
    "maxFirmSize": 100
  },
  "chart": {
    "label": " Spend by Law Firm",
    "value": "SpendByFirm"
  }
};
