import {ITag} from '../../../practice-area/practice-area.model';

export const MOCK_PLACTICE_AREA = {
  client_matter_type: 'LITIGATION',
  active: true,
  boutique: '',
  crawl_id: 1,
  crawlable: '',
  is_javascript: true,
  is_sitemap: true,
  is_proxy_crawl: true,
  bio_config_file: '',
  news_config_file: '',
  leverage: 1,
  average_partner_rate: 1,
  average_associate_rate: 1,
  estimated_number_lawyers: 1,
  synonym_primary_id: 1,
  json_config: '',
  logo_url: '',
  tags: [],
  yearly_stats: []
};

export const MOCK_PRACTICE_AREAS = {
  "result": ["AVIATION CASUALTY / AEROSPACE", "EMPLOYMENT NON DUTY", "CONSTRUCTION DEFECT COVERAGE", "HPL/MEDMAL", "EXCESS", "HEALTH MAINTENANCE ORGANIZATIO", "PROPERTY", "FEDERAL BLACK LUNG", "TOXIC TORT", "#N/A", "INTELLECTUAL PROPERTY", "ENVIRONMENTAL COVERAGE", "COVERAGE", "WORKERS COMP (AFA) HO SPECIFIC", "ENVIRONMENTAL", "AUTO & PERSONAL LINES", "WAR HAZARD RECOVERY (AFA)", "PROPERTY COVERAGE", "PUBLIC ENTITY", "FINANCIAL INSTITUTIONS", "WORKERS COMP", "FIDELITY & SURETY", "PROFESSIONAL LIABILITY (AFA)", "MISCELLANEOUG PROF LIABILITY", "POLLUTION INSURANCE PRODUCTS", "CASUALTY", "SUBROGATION", "BANKRUPTCY", "TECH/MEDIA", "DIRECTORS & OFFICERS", "COMMERCIAL GROUND TRANSP.", "SCHOOL LEADERS", "WILLIS SKI PROGRAM (ASDA)", "CVS - WORKERS` COMPENSATION", "COMPLEX", "ARCHITECTS & ENGINEERS", "TAKATA", "MOLD", "CONSTRUCTION RISK", "PROFESSIONAL LIABILITY", "CONSTRUCTION DEFECT (AFA)", "BAD FAITH", "SURETY", "NATIONAL UNION MONITORING", "JC PENNEY CASUALTY CASES", "EMP. RELATED PRACTICES (AFA)", "SCHOOL CONSTRUCTION AUTHORITY", "USL&H LONG SHORE & HARBOR WC", "CLASS ACTION", "FINANCIAL LINES COVERAGE", "CASUALTY (AFA)", "APPELLATE", "DEFENSE BASE ACT", "EMP.RELATED PRACTICES", "WORKERS COMP COVERAGE", "CONSTRUCTION DEFECT", "JC PENNEY WORKERS COMP", "PRODUCTS LIABILITY"],
  "error": null
};
export const MOCK_MIN_MAX_DATES = {
  "result": {
    "min": "2017-06-24",
    "max": "2019-06-24"
  },
  "error": null
};
