export const MOCK_QUARTER_DATES = {
    "monthNumbers": [
        3,
        6,
        9,
        12
    ],
    "formattedQuarterDates": [
        "03-01",
        "06-01",
        "09-01",
        "12-01"
    ]
};

export const MOCK_GENERIC_QBR_RECOMMENDATIONS = [
  {
      "id": 1,
      "title": "Increase Discounts",
      "opportunity": "Obtain greater relationship and practice area discounts to reduce net effective rates.",
      "why_it_matters": "All firms are willing to negotiate discounts based on relationship, practice area or volume and these discounts can be highly impactful for managing legal spend.",
      "action": "1. Evaluate current discount and ask for increase\n2. Ensure firms are required to obtain agreement before attempting to increase rates or decrease discounts",
      "created_by": "sys",
      "created_on": "2021-11-15T13:51:49.156981",
      "deleted_by": null,
      "deleted_on": null,
      "modified_by": null,
      "modified_on": null
  },
  {
      "id": 2,
      "title": "Prevent Rate Increases",
      "opportunity": "Freeze billing rates YoY or hold down rate increases to below 2-3%",
      "why_it_matters": "Holding down rate increases is an essential tool to reduce legal fees and ensure you're paying appropriate rates to your firms",
      "action": "1. Review net effective rates YoY\n2. Identify any proposed or actual rate increases\n3. Negotiate with firms top prevent rate increases",
      "created_by": "sys",
      "created_on": "2021-11-15T13:51:49.156981",
      "deleted_by": null,
      "deleted_on": null,
      "modified_by": null,
      "modified_on": null
  },
  {
      "id": 3,
      "title": "Partner / Associate Work Allocation",
      "opportunity": "Client should aim to increase or maintain associate work allocation at 65% or more of all attorney hours, keeping partner percentage of hours below 35% ",
      "why_it_matters": "Allocating work to associates reduces costs and associates are the appropriate attorney level for most attorney work, save for complex/strategic work warranting partner involvement",
      "action": "1. Evaluate partner and associate percentage of hours worked;\n2. Ensure partner percentage is kept below 35% and aim to keep partner work on matters at [ Firm ] to ensure the lowest cost timekeeper qualified is performing the work; \n3. Communicate expectations to [ Firm ] ",
      "created_by": "sys",
      "created_on": "2021-11-15T13:51:49.156981",
      "deleted_by": null,
      "deleted_on": null,
      "modified_by": null,
      "modified_on": null
  },
  {
      "id": 4,
      "title": "Decrease Block Billing",
      "opportunity": "",
      "why_it_matters": "Limiting block billing practices results in more accurate timekeeping and reduces inflationary billing practices.",
      "action": "1. Review percentage of block billing \n2. Pay [ Firm ] a reduced amount for block billed work \n3. Communicate to firms the requirement that block billing above 20% of time is not acceptable.",
      "created_by": "sys",
      "created_on": "2021-11-15T13:51:49.156981",
      "deleted_by": null,
      "deleted_on": null,
      "modified_by": null,
      "modified_on": null
  },
  {
      "id": 5,
      "title": "Shift Work to Other Firms",
      "opportunity": "Significant savings are available when comparing the efficiency of your firms and moving work to more cost-effective firms.",
      "why_it_matters": "While focus on rates and work allocation can be effective, firm selection offers even greater savings opportunities.",
      "action": "1. Identify lower-cost firms who can take on more work\n2. Provide work, where appropriate, to best available lower-cost firms, instead of higher-cost firms",
      "created_by": "sys",
      "created_on": "2021-11-15T13:51:49.156981",
      "deleted_by": null,
      "deleted_on": null,
      "modified_by": null,
      "modified_on": null
  },
  {
      "id": 6,
      "title": "Custom Recommendation",
      "opportunity": "Custom                                           ",
      "why_it_matters": "Custom                                           ",
      "action": "Custom                                           ",
      "created_by": "sys",
      "created_on": "2021-11-15T13:51:49.156981",
      "deleted_by": null,
      "deleted_on": null,
      "modified_by": null,
      "modified_on": null
  }
];

export const MOCK_QBR = {
  "id": 276,
  "bh_client_id": 113,
  "title": "Quarterly Business Review for Bloomberg",
  "report_type": "QoQAdjacent",
  "filters": {
      "name": "filters",
      "filters": [
          {
              "step": 0.25,
              "type": "NUMERIC",
              "value": 4,
              "default": 4,
              "display": true,
              "exclude": false,
              "ordered": false,
              "preload": 0,
              "isCapped": false,
              "maxRange": 0,
              "minRange": 0,
              "fieldName": "threshold",
              "displayName": "Hour Threshold",
              "filterGroup": "Threshold",
              "isMatterTag": false,
              "matterCollection": ""
          },
          {
              "step": 500,
              "type": "NUMERIC",
              "value": 0,
              "default": 0,
              "display": true,
              "exclude": false,
              "ordered": false,
              "preload": 0,
              "isCapped": false,
              "maxRange": 0,
              "minRange": 0,
              "fieldName": "dollar_threshold",
              "displayName": "Dollar Threshold",
              "filterGroup": "Threshold",
              "isMatterTag": false,
              "matterCollection": ""
          },
          {
              "type": "MULTISELECT",
              "value": [],
              "display": true,
              "exclude": false,
              "ordered": false,
              "preload": 0,
              "isCapped": false,
              "maxRange": 0,
              "minRange": 0,
              "fieldName": "firms",
              "displayName": "Firms",
              "filterGroup": "Firms",
              "isMatterTag": false,
              "matterCollection": ""
          },
          {
              "type": "MULTISELECT",
              "value": [],
              "display": true,
              "exclude": false,
              "ordered": false,
              "preload": 0,
              "isCapped": false,
              "maxRange": 0,
              "minRange": 0,
              "fieldName": "matterNames",
              "displayName": "Matter Names",
              "filterGroup": "Matters",
              "isMatterTag": false,
              "matterCollection": ""
          },
          {
              "type": "MULTISELECT",
              "value": [],
              "display": true,
              "exclude": false,
              "ordered": false,
              "preload": 0,
              "isCapped": false,
              "maxRange": 0,
              "minRange": 0,
              "fieldName": "matters",
              "displayName": "Matter IDs",
              "filterGroup": "Matters",
              "isMatterTag": false,
              "matterCollection": ""
          },
          {
              "type": "MULTISELECT",
              "value": [],
              "display": true,
              "exclude": false,
              "ordered": false,
              "preload": 0,
              "isCapped": false,
              "maxRange": 0,
              "minRange": 0,
              "fieldName": "geographies",
              "displayName": "Geographies",
              "filterGroup": "Internal",
              "isMatterTag": false,
              "matterCollection": ""
          },
          {
              "type": "MULTISELECT",
              "value": [],
              "display": true,
              "exclude": false,
              "ordered": false,
              "preload": 0,
              "isCapped": false,
              "maxRange": 0,
              "minRange": 0,
              "fieldName": "utbmsCodes",
              "displayName": "Task Codes",
              "filterGroup": "Matters",
              "isMatterTag": false,
              "matterCollection": ""
          },
          {
              "type": "MULTISELECT",
              "value": [],
              "display": true,
              "exclude": false,
              "ordered": false,
              "preload": 0,
              "isCapped": false,
              "maxRange": 0,
              "minRange": 0,
              "fieldName": "firmTypes",
              "displayName": "Firm Types",
              "filterGroup": "Firms",
              "isMatterTag": false,
              "matterCollection": ""
          },
          {
              "type": "MULTISELECT",
              "value": [],
              "display": true,
              "exclude": false,
              "ordered": false,
              "preload": 0,
              "isCapped": false,
              "maxRange": 0,
              "minRange": 0,
              "fieldName": "bdPracticeAreas",
              "displayName": "Smart Practice Areas",
              "filterGroup": "Practice Areas",
              "isMatterTag": false,
              "matterCollection": ""
          },
          {
              "type": "DATERANGE",
              "value": {
                  "endDate": "2021-03-10T05:00:00.000Z",
                  "startDate": "2019-03-10T05:00:00.000Z"
              },
              "display": true,
              "exclude": false,
              "maxDate": "2021-03-10",
              "minDate": "2014-06-30",
              "ordered": false,
              "preload": 0,
              "isCapped": false,
              "maxRange": 0,
              "minRange": 0,
              "fieldName": "dateRange",
              "displayName": "Date Range",
              "filterGroup": "Dates",
              "isMatterTag": false,
              "matterCollection": ""
          },
          {
              "type": "DATERANGE",
              "value": {
                  "endDate": "2021-03-10T05:00:00.000Z",
                  "startDate": "2019-03-10T05:00:00.000Z"
              },
              "display": true,
              "exclude": false,
              "maxDate": "2020-07-04",
              "minDate": "2020-07-04",
              "ordered": false,
              "preload": 0,
              "isCapped": false,
              "maxRange": 0,
              "minRange": 0,
              "fieldName": "datePaid",
              "displayName": "Date Paid Range",
              "filterGroup": "Dates",
              "isMatterTag": false,
              "matterCollection": ""
          },
          {
              "type": "DATERANGE",
              "value": {
                  "endDate": "2021-03-10T05:00:00.000Z",
                  "startDate": "2019-03-10T05:00:00.000Z"
              },
              "display": true,
              "exclude": false,
              "maxDate": "2020-08-05",
              "minDate": "2020-08-05",
              "ordered": false,
              "preload": 0,
              "isCapped": false,
              "maxRange": 0,
              "minRange": 0,
              "fieldName": "invoiceDate",
              "displayName": "Invoice Date Range",
              "filterGroup": "Dates",
              "isMatterTag": false,
              "matterCollection": ""
          },
          {
              "type": "RANGESLIDER",
              "value": [
                  1,
                  1000
              ],
              "display": true,
              "exclude": false,
              "ordered": false,
              "preload": 0,
              "isCapped": true,
              "maxRange": 1000,
              "minRange": 1,
              "fieldName": "firmMatterCount",
              "displayName": "Number of Matters",
              "filterGroup": "Firms",
              "isMatterTag": false,
              "matterCollection": ""
          },
          {
              "type": "MULTISELECT",
              "value": [],
              "display": true,
              "exclude": false,
              "ordered": false,
              "preload": 0,
              "isCapped": false,
              "maxRange": 0,
              "minRange": 0,
              "fieldName": "leadPartners",
              "displayName": "Lead Partners",
              "filterGroup": "Firms",
              "isMatterTag": false,
              "matterCollection": ""
          },
          {
              "step": 50000,
              "type": "RANGESLIDER",
              "value": [
                  0,
                  4850000
              ],
              "display": true,
              "exclude": false,
              "ordered": false,
              "preload": 0,
              "isCapped": true,
              "maxRange": 4850000,
              "minRange": 0,
              "fieldName": "matterCost",
              "displayName": "Total Matter Cost",
              "filterGroup": "Matters",
              "isMatterTag": false,
              "matterCollection": ""
          },
          {
              "step": 50,
              "type": "RANGESLIDER",
              "value": [
                  1,
                  500
              ],
              "display": true,
              "exclude": false,
              "ordered": false,
              "preload": 0,
              "isCapped": true,
              "maxRange": 500,
              "minRange": 1,
              "fieldName": "firmSize",
              "displayName": "Firm Size (Attorneys)",
              "filterGroup": "Firms",
              "isMatterTag": false,
              "matterCollection": ""
          },
          {
              "type": "SELECT",
              "value": null,
              "display": true,
              "exclude": false,
              "options": [
                  {
                      "label": "-Select-",
                      "value": null
                  },
                  {
                      "label": "Closed",
                      "value": "Closed"
                  },
                  {
                      "label": "Open",
                      "value": "Open"
                  }
              ],
              "ordered": false,
              "preload": 0,
              "isCapped": false,
              "maxRange": 0,
              "minRange": 0,
              "fieldName": "matterStatus",
              "displayName": "Matter Status",
              "filterGroup": "Matters",
              "isMatterTag": false,
              "matterCollection": ""
          },
          {
              "type": "DATE",
              "value": null,
              "display": true,
              "exclude": false,
              "ordered": false,
              "preload": 0,
              "isCapped": false,
              "maxRange": 0,
              "minRange": 0,
              "fieldName": "matterOpenDateStart",
              "displayName": "Matter Open Date Start",
              "filterGroup": "Matters",
              "isMatterTag": false,
              "matterCollection": ""
          },
          {
              "type": "DATE",
              "value": null,
              "display": true,
              "exclude": false,
              "ordered": false,
              "preload": 0,
              "isCapped": false,
              "maxRange": 0,
              "minRange": 0,
              "fieldName": "matterOpenDateEnd",
              "displayName": "Matter Open Date End",
              "filterGroup": "Matters",
              "isMatterTag": false,
              "matterCollection": ""
          },
          {
              "type": "DATE",
              "value": null,
              "display": true,
              "exclude": false,
              "ordered": false,
              "preload": 0,
              "isCapped": false,
              "maxRange": 0,
              "minRange": 0,
              "fieldName": "matterCloseDateStart",
              "displayName": "Matter Close Date Start",
              "filterGroup": "Matters",
              "isMatterTag": false,
              "matterCollection": ""
          },
          {
              "type": "DATE",
              "value": null,
              "display": true,
              "exclude": false,
              "ordered": false,
              "preload": 0,
              "isCapped": false,
              "maxRange": 0,
              "minRange": 0,
              "fieldName": "matterCloseDateEnd",
              "displayName": "Matter Close Date End",
              "filterGroup": "Matters",
              "isMatterTag": false,
              "matterCollection": ""
          },
          {
              "type": "DAYOFMATTER",
              "value": {
                  "dayOfMatter1": null,
                  "dayOfMatter2": null,
                  "dayOfMatterRange": null
              },
              "display": true,
              "exclude": false,
              "options": [
                  {
                      "label": "-Select-",
                      "value": null
                  },
                  {
                      "label": "First",
                      "value": "First"
                  },
                  {
                      "label": "Last",
                      "value": "Last"
                  },
                  {
                      "label": "Between",
                      "value": "Between"
                  }
              ],
              "ordered": false,
              "preload": 0,
              "isCapped": false,
              "maxRange": 0,
              "minRange": 0,
              "fieldName": "dayOfMatter",
              "displayName": "Day of Matter",
              "filterGroup": "Matters",
              "isMatterTag": false,
              "matterCollection": ""
          },
          {
              "type": "SELECT",
              "value": null,
              "display": true,
              "exclude": false,
              "options": null,
              "ordered": false,
              "preload": 0,
              "isCapped": false,
              "maxRange": 0,
              "minRange": 0,
              "fieldName": "matterTagCollections",
              "displayName": "Matter Tag Collections",
              "filterGroup": "Matters",
              "isMatterTag": false,
              "matterCollection": ""
          }
      ]
  },
  "chosen_metrics": {
      "total_spend": true,
      "blended_rate": false,
      "bodhala_price_index": false,
      "partner_hourly_cost": true,
      "associate_hourly_cost": true,
      "block_billing_percent": true,
      "partner_hours_percent": true,
      "associate_hours_percent": true
  },
  "start_date": "2019-03-01",
  "end_date": "2019-05-31",
  "querystring": {
      "enddate": "2021-03-10",
      "clientId": 113,
      "expenses": true,
      "startdate": "2019-03-10",
      "threshold": "4"
  },
  "status": "IN PROGRESS",
  "created_by": "447",
  "created_on": "2021-11-16T10:02:02.097703",
  "deleted_by": null,
  "deleted_on": null,
  "modified_by": "447",
  "modified_on": "2021-11-17T09:24:45.804704"
};


export const MOCK_SAVED_QBR_RECOMMENDATIONS = [
  {
      "id": 350,
      "qbr_id": 276,
      "recommendation_type_id": 1,
      "practice_area": null,
      "firm_id": null,
      "title": "Increase Discounts",
      "subtitle": null,
      "opportunity": "Obtain greater relationship and practice area discounts to reduce net effective rates.",
      "why_it_matters": "All firms are willing to negotiate discounts based on relationship, practice area or volume and these discounts can be highly impactful for managing legal spend.",
      "recommendation": "$10,065,011\nTotal Spend\n12.8%\nTotal Spend Trend",
      "section": "Insights",
      "included": true,
      "created_on": "2021-11-17T09:24:50.578652",
      "deleted_on": null,
      "created_by": "447",
      "type": "Increase Discounts",
      "firm_name": null,
      "corresponding_insight_id": null,
      "recommended_discount_pct_lower_range": null,
      "recommended_discount_pct_upper_range": null,
      "current_discount_pct": null,
      "spend_increase_pct": null,
      "rate_increase_pct": null,
      "desired_rate_increase_pct": null,
      "previous_firm_ids": null,
      "recommended_firm_ids": null,
      "desired_partner_pct_of_hours_worked": null,
      "desired_associate_pct_of_hours_worked": null,
      "desired_paralegal_pct_of_hours_worked": null,
      "desired_block_billing_pct": null,
      "potential_savings": null
  },
  {
      "id": 351,
      "qbr_id": 276,
      "recommendation_type_id": 2,
      "practice_area": null,
      "firm_id": null,
      "title": "Prevent Rate Increases",
      "subtitle": null,
      "opportunity": "Freeze billing rates YoY or hold down rate increases to below 2-3%",
      "why_it_matters": "Holding down rate increases is an essential tool to reduce legal fees and ensure you're paying appropriate rates to your firms",
      "recommendation": "14.7%\nAvg. Assoc Rate Increase\n-7.6%\nAvg. Partner Rate Increase",
      "section": "Insights",
      "included": true,
      "created_on": "2021-11-17T09:24:51.802240",
      "deleted_on": null,
      "created_by": "447",
      "type": "Prevent Rate Increases",
      "firm_name": null,
      "corresponding_insight_id": null,
      "recommended_discount_pct_lower_range": null,
      "recommended_discount_pct_upper_range": null,
      "current_discount_pct": null,
      "spend_increase_pct": null,
      "rate_increase_pct": null,
      "desired_rate_increase_pct": null,
      "previous_firm_ids": null,
      "recommended_firm_ids": null,
      "desired_partner_pct_of_hours_worked": null,
      "desired_associate_pct_of_hours_worked": null,
      "desired_paralegal_pct_of_hours_worked": null,
      "desired_block_billing_pct": null,
      "potential_savings": null
  },
  {
      "id": 352,
      "qbr_id": 276,
      "recommendation_type_id": 3,
      "practice_area": null,
      "firm_id": null,
      "title": "Partner / Associate Work Allocation",
      "subtitle": null,
      "opportunity": "Client should aim to increase or maintain associate work allocation at 65% or more of all attorney hours, keeping partner percentage of hours below 35% ",
      "why_it_matters": "Allocating work to associates reduces costs and associates are the appropriate attorney level for most attorney work, save for complex/strategic work warranting partner involvement",
      "recommendation": "$939\nAvg. Partner Rate\n19.8%\nPartner Hours Billed",
      "section": "Insights",
      "included": true,
      "created_on": "2021-11-17T09:24:55.017996",
      "deleted_on": null,
      "created_by": "447",
      "type": "Partner / Associate Work Allocation",
      "firm_name": null,
      "corresponding_insight_id": null,
      "recommended_discount_pct_lower_range": null,
      "recommended_discount_pct_upper_range": null,
      "current_discount_pct": null,
      "spend_increase_pct": null,
      "rate_increase_pct": null,
      "desired_rate_increase_pct": null,
      "previous_firm_ids": null,
      "recommended_firm_ids": null,
      "desired_partner_pct_of_hours_worked": null,
      "desired_associate_pct_of_hours_worked": null,
      "desired_paralegal_pct_of_hours_worked": null,
      "desired_block_billing_pct": null,
      "potential_savings": null
  },
  {
      "id": 353,
      "qbr_id": 276,
      "recommendation_type_id": 1,
      "practice_area": null,
      "firm_id": null,
      "title": "Increase Discounts",
      "subtitle": null,
      "opportunity": "Obtain greater relationship and practice area discounts to reduce net effective rates.",
      "why_it_matters": "All firms are willing to negotiate discounts based on relationship, practice area or volume and these discounts can be highly impactful for managing legal spend.",
      "recommendation": "1. Evaluate current discount and ask for increase\n2. Ensure firms are required to obtain agreement before attempting to increase rates or decrease discounts",
      "section": "Next Steps",
      "included": true,
      "created_on": "2021-11-17T09:24:58.662461",
      "deleted_on": null,
      "created_by": "447",
      "type": "Increase Discounts",
      "firm_name": null,
      "corresponding_insight_id": 350,
      "recommended_discount_pct_lower_range": 5,
      "recommended_discount_pct_upper_range": null,
      "current_discount_pct": 0,
      "spend_increase_pct": 0,
      "rate_increase_pct": null,
      "desired_rate_increase_pct": null,
      "previous_firm_ids": null,
      "recommended_firm_ids": null,
      "desired_partner_pct_of_hours_worked": null,
      "desired_associate_pct_of_hours_worked": null,
      "desired_paralegal_pct_of_hours_worked": null,
      "desired_block_billing_pct": null,
      "potential_savings": 503250.558715
  },
  {
      "id": 354,
      "qbr_id": 276,
      "recommendation_type_id": 2,
      "practice_area": null,
      "firm_id": null,
      "title": "Prevent Rate Increases",
      "subtitle": null,
      "opportunity": "Freeze billing rates YoY or hold down rate increases to below 2-3%",
      "why_it_matters": "Holding down rate increases is an essential tool to reduce legal fees and ensure you're paying appropriate rates to your firms",
      "recommendation": "1. Review net effective rates YoY\n2. Identify any proposed or actual rate increases\n3. Negotiate with firms top prevent rate increases",
      "section": "Next Steps",
      "included": true,
      "created_on": "2021-11-17T09:24:59.138488",
      "deleted_on": null,
      "created_by": "447",
      "type": "Prevent Rate Increases",
      "firm_name": null,
      "corresponding_insight_id": 351,
      "recommended_discount_pct_lower_range": null,
      "recommended_discount_pct_upper_range": null,
      "current_discount_pct": null,
      "spend_increase_pct": 0,
      "rate_increase_pct": null,
      "desired_rate_increase_pct": 3,
      "previous_firm_ids": null,
      "recommended_firm_ids": null,
      "desired_partner_pct_of_hours_worked": null,
      "desired_associate_pct_of_hours_worked": null,
      "desired_paralegal_pct_of_hours_worked": null,
      "desired_block_billing_pct": null,
      "potential_savings": -1765.7118959598656
  },
  {
      "id": 355,
      "qbr_id": 276,
      "recommendation_type_id": 3,
      "practice_area": null,
      "firm_id": null,
      "title": "Partner / Associate Work Allocation",
      "subtitle": null,
      "opportunity": "Client should aim to increase or maintain associate work allocation at 65% or more of all attorney hours, keeping partner percentage of hours below 35% ",
      "why_it_matters": "Allocating work to associates reduces costs and associates are the appropriate attorney level for most attorney work, save for complex/strategic work warranting partner involvement",
      "recommendation": "ensure the lowest cost timekeeper qualified is performing the work; \n3. Communicate expectations to your firms ",
      "section": "Next Steps",
      "included": true,
      "created_on": "2021-11-17T09:25:02.410680",
      "deleted_on": null,
      "created_by": "447",
      "type": "Partner / Associate Work Allocation",
      "firm_name": null,
      "corresponding_insight_id": 352,
      "recommended_discount_pct_lower_range": null,
      "recommended_discount_pct_upper_range": null,
      "current_discount_pct": null,
      "spend_increase_pct": 0,
      "rate_increase_pct": null,
      "desired_rate_increase_pct": null,
      "previous_firm_ids": null,
      "recommended_firm_ids": null,
      "desired_partner_pct_of_hours_worked": 35,
      "desired_associate_pct_of_hours_worked": 65,
      "desired_paralegal_pct_of_hours_worked": 0,
      "desired_block_billing_pct": null,
      "potential_savings": -91994.91201968491
  }
];
